name: Slither Audit

on:
  workflow_dispatch:

jobs:
  slither:
    name: Run Slither
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dgtenergy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip solc npm

      - name: Install Node dependencies (OpenZeppelin)
        run: |
          npm init -y
          npm install @openzeppelin/contracts

      - name: Install Slither
        run: |
          pip3 install slither-analyzer

      - name: Run Slither on contracts
        run: slither ./src/contracts --solc-remaps "@openzeppelin=node_modules/@openzeppelin"
