name: Slither Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Slither
        run: |
          pip install slither-analyzer

      - name: Install Node Dependencies
        run: |
          npm install

      - name: Run Slither
        run: |
          slither src/contracts/
